-d /home/carlos/Embedded/litex_work/femtorv/basic/gowin/impl/gwsynthesis/project.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst /home/carlos/Embedded/litex_work/femtorv/basic/gowin/soc_femto.cst
-cfg /home/carlos/Embedded/litex_work/femtorv/basic/gowin/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
